DELETE FROM todos; DELETE FROM projects; DELETE FROM settings; DELETE FROM agenda_events;
INSERT INTO todos (text, done, priority, date) VALUES ('Voorstel tijdens productspecialistenoverleg  mb Artikelen en Claude', 0, 'Vandaag', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Zendesk-widget testen op Parro/Schoolkassa', 0, 'Vandaag', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Ticket 591132 op opgelost per 7 augustus', 1, 'Geen datum', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Artikel logboek Parro Portaal schrijven', 0, 'Vandaag', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Artikel schrijven over media download + darkmoad', 1, 'Vandaag', '2026-07-02');
INSERT INTO todos (text, done, priority, date) VALUES ('Parro Portaal Beheer artikel verwerken in Starten met Parro Portaal', 0, 'Vandaag', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Kijken naar Kennisportaal artikel Starten met Parro', 0, 'Vandaag', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Artikel 2FA controleren op bovenschools afgedwongen -> Uitschakelen medewerkers', 0, 'Vandaag', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Parro Portaal: Digitaal ondertekenen OPP artikel schrijven', 0, 'Vandaag', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Parro Vertalen artikel schrijven', 0, 'Vandaag', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Schoolkassa Buckaroo artikel doorlezen en additionele accounts toevoegen', 0, 'Vandaag', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Zendesk-widget Digitaal Ondertekenen OPP aan Mark vragen', 0, 'Vandaag', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Parro Vertalen artikel Ouders schrijven', 0, 'Vandaag', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Parro Vertalen: Instellingen vertalen uitzetten', 0, 'Vandaag', NULL);
INSERT INTO todos (text, done, priority, date) VALUES ('Parro fusie/splitsing mails doornemen, contact met Marketing over datum', 0, 'Vandaag', NULL);
INSERT INTO projects (name, pct, status, deadline, color, subtasks) VALUES ('Schoolkassa interne FAQ', 40, 'Actief', '2026-06-30', '#C8F55A', '[{"text":"Vragen opstellen","done":true},{"text":"Tickets erbij zoeken","done":true},{"text":"Antwoorden formuleren","done":false},{"text":"Loes laten nakijken","done":false},{"text":"Afbeeldingen toevoegen","done":false}]');
INSERT INTO projects (name, pct, status, deadline, color, subtasks) VALUES ('Schooljaarstart presentatie', 0, 'Actief', '2026-08-20', '#6BA8FF', NULL);
INSERT INTO projects (name, pct, status, deadline, color, subtasks) VALUES ('Artikelen Parro Portaal', 0, 'Actief', '', '#5BDB8A', NULL);
INSERT INTO projects (name, pct, status, deadline, color, subtasks) VALUES ('Artikelen overstap Schoolkassa Buckaroo', 0, 'Actief', '', '#FFB84D', NULL);
INSERT INTO projects (name, pct, status, deadline, color, subtasks) VALUES ('Kennisartikel Starten met Parro', 0, 'Actief', '', '#FF6B6B', NULL);
INSERT INTO settings (key, value) VALUES ("user_settings", '{"slackName":"Rick de Jong","theme":"dark","accent":"#C8F55A","accentText":"#0E0E0C","colorName":"lime"}');
INSERT INTO settings (key, value) VALUES ("hidden_projects", '[]');
INSERT INTO settings (key, value) VALUES ("agenda_meta", '{"updatedAt":"2026-08-17T09:54:01.394Z","date":"17-8-2026"}');
INSERT INTO agenda_events (subject, start, end, location, join_url) VALUES ('0641271841 bellen ivm 605560', '2026-08-17T09:30:00.0000000', '2026-08-17T10:00:00.0000000', '', NULL);
INSERT INTO agenda_events (subject, start, end, location, join_url) VALUES ('Buckaroo multi-accounts', '2026-08-17T13:00:00.0000000', '2026-08-17T13:45:00.0000000', 'VK LB 2.6 Schoolplein (10)', NULL);
INSERT INTO agenda_events (subject, start, end, location, join_url) VALUES ('Buckaroo-artikelen schrijven', '2026-08-18T06:30:00.0000000', '2026-08-18T10:30:00.0000000', '', NULL);
INSERT INTO agenda_events (subject, start, end, location, join_url) VALUES ('Ticket 605787', '2026-08-18T13:00:00.0000000', '2026-08-18T13:30:00.0000000', 'Microsoft Teams-vergadering', NULL);
INSERT INTO agenda_events (subject, start, end, location, join_url) VALUES ('Bug prioriteiten sessie met Productspecialisten', '2026-08-20T12:00:00.0000000', '2026-08-20T13:00:00.0000000', 'VK LB 3.1 Peperbus (10)', NULL);
INSERT INTO agenda_events (subject, start, end, location, join_url) VALUES ('Kennissessie schooljaarstart 2026', '2026-08-20T13:00:00.0000000', '2026-08-20T14:00:00.0000000', 'VK LB 2.5 Lerarenkamer (12)', NULL);
INSERT INTO agenda_events (subject, start, end, location, join_url) VALUES ('Schoolkassa Review', '2026-08-17T11:00:00.0000000', '2026-08-17T11:45:00.0000000', 'VK LB 2.5 Lerarenkamer (12)', NULL);
INSERT INTO agenda_events (subject, start, end, location, join_url) VALUES ('AI inloopspreekuur', '2026-08-20T09:00:00.0000000', '2026-08-20T10:00:00.0000000', 'club topicana', NULL);
